# Data Profiling
**Team:** Sage Kim & Kyna Tyagi

## 0. SHA-256 Checksum Verification

In [7]:
import hashlib

def get_sha256(filepath):
    with open(filepath, 'rb') as f:
        return hashlib.sha256(f.read()).hexdigest()

fao_hash = get_sha256('../data/raw/faostat_cereal_raw.csv')
wb_hash  = get_sha256('../data/raw/worldbank_gdp_raw.csv')

print('faostat_cereal_raw.csv :', fao_hash)
print('worldbank_gdp_raw.csv  :', wb_hash)

# Save checksums to file
with open('../data/raw/checksums.txt', 'w') as f:
    f.write(f'{fao_hash}  faostat_cereal_raw.csv\n')
    f.write(f'{wb_hash}  worldbank_gdp_raw.csv\n')

print('\nSaved to data/raw/checksums.txt')

faostat_cereal_raw.csv : 4a6a8cb3d2e1e97ed7e515db1581b4f08825d9b270b6363db498c67914ab9ca4
worldbank_gdp_raw.csv  : ac45ccf04996ae4170d80313ab2abc328cf7736b249c6adef4485a644ac8b128

Saved to data/raw/checksums.txt

In [ ]:
import pandas as pd
import matplotlib.pyplot as plt

# Load raw datasets
fao = pd.read_csv('../data/raw/faostat_cereal_raw.csv')
wb  = pd.read_csv('../data/raw/worldbank_gdp_raw.csv', skiprows=4)

---
## 1. FAO Dataset

In [53]:
# Basic structure
print('FAO shape:', fao.shape)
print(fao.columns.tolist())
print(fao.dtypes)
fao.head()

FAO shape: (3008, 15)
['Domain Code', 'Domain', 'Area Code (M49)', 'Area', 'Element Code', 'Element', 'Item Code (CPC)', 'Item', 'Year Code', 'Year', 'Unit', 'Value', 'Flag', 'Flag Description', 'Note']
Domain Code          object
Domain               object
Area Code (M49)       int64
Area                 object
Element Code          int64
Element              object
Item Code (CPC)     float64
Item                 object
Year Code             int64
Year                  int64
Unit                 object
Value               float64
Flag                 object
Flag Description     object
Note                 object
dtype: object

,Domain Code,Domain,Area Code (M49),Area,Element Code,Element,Item Code (CPC),Item,Year Code,Year,Unit,Value,Flag,Flag Description,Note
0,QCL,Crops and livestock products,32,Argentina,5510,Production,1199.9,Cereals n.e.c.,1961,1961,t,16000.0,A,Official figure,NaN
1,QCL,Crops and livestock products,32,Argentina,5510,Production,1199.9,Cereals n.e.c.,1962,1962,t,14000.0,A,Official figure,NaN
2,QCL,Crops and livestock products,32,Argentina,5510,Production,1199.9,Cereals n.e.c.,1963,1963,t,15000.0,A,Official figure,NaN
3,QCL,Crops and livestock products,32,Argentina,5510,Production,1199.9,Cereals n.e.c.,1964,1964,t,17000.0,A,Official figure,NaN
4,QCL,Crops and livestock products,32,Argentina,5510,Production,1199.9,Cereals n.e.c.,1965,1965,t,20000.0,A,Official figure,NaN

In [56]:
# Coverage
print('Num of Countries:', fao['Area'].nunique())
print('Year range:', fao['Year'].min(), '~', fao['Year'].max())

Num of Countries: 71
Year range: 1961 ~ 2024

In [ ]:
# Missing Values
print(fao.isnull().sum())

Domain Code            0
Domain                 0
Area Code (M49)        0
Area                   0
Element Code           0
Element                0
Item Code (CPC)        0
Item                   0
Year Code              0
Year                   0
Unit                   0
Value                392
Flag                   0
Flag Description       0
Note                2888
dtype: int64

In [40]:
# Duplicates
print(fao.duplicated().sum())

0

In [ ]:
# Production Value Distribution (Outliers)
print(fao['Value'].describe().round(2))

count       2616.00
mean       76231.31
std       440663.39
min            0.00
25%         1302.22
50%         5495.00
75%        18000.00
max      6019040.01
Name: Value, dtype: float64

In [ ]:
# Country Names
print((fao['Area'].unique()))

['Argentina' 'Armenia' 'Austria' 'Belarus' 'Belgium' 'Bhutan'
 'Bolivia (Plurinational State of)' 'Botswana' 'Bulgaria' 'Burundi' 'Chad'
 'China' 'China, mainland' 'China, Taiwan Province of' 'Colombia' 'Congo'
 'Croatia' 'Czechia' 'Czechoslovakia' 'Eritrea' 'Estonia' 'Ethiopia'
 'Ethiopia PDR' 'Finland' 'France' 'Gambia' 'Georgia' 'Greece'
 'Guinea-Bissau' 'Hungary' 'Ireland' 'Italy' 'Jordan' 'Kazakhstan'
 'Latvia' 'Lithuania' 'Luxembourg' 'Mali' 'Malta' 'Mexico' 'Mongolia'
 'Morocco' 'Myanmar' 'New Zealand' 'Niger' 'Oman' 'Palestine' 'Peru'
 'Poland' 'Portugal' 'Qatar' 'Republic of Korea' 'Romania'
 'Russian Federation' 'Saudi Arabia' 'Senegal' 'Serbia' 'Sierra Leone'
 'Slovakia' 'Slovenia' 'South Africa' 'Spain' 'Switzerland' 'Thailand'
 'Togo' 'Tunisia' 'Ukraine' 'United Republic of Tanzania' 'USSR'
 'Uzbekistan' 'Zimbabwe']

---
## 2. World Bank Dataset

In [55]:
# Basic structure
print('World Bank shape:', wb.shape)
print(wb.columns.tolist())
print(wb.dtypes[:8])
wb.head()

World Bank shape: (266, 71)
['Country Name', 'Country Code', 'Indicator Name', 'Indicator Code', '1960', '1961', '1962', '1963', '1964', '1965', '1966', '1967', '1968', '1969', '1970', '1971', '1972', '1973', '1974', '1975', '1976', '1977', '1978', '1979', '1980', '1981', '1982', '1983', '1984', '1985', '1986', '1987', '1988', '1989', '1990', '1991', '1992', '1993', '1994', '1995', '1996', '1997', '1998', '1999', '2000', '2001', '2002', '2003', '2004', '2005', '2006', '2007', '2008', '2009', '2010', '2011', '2012', '2013', '2014', '2015', '2016', '2017', '2018', '2019', '2020', '2021', '2022', '2023', '2024', '2025', 'Unnamed: 70']
Country Name       object
Country Code       object
Indicator Name     object
Indicator Code     object
1960              float64
1961              float64
1962              float64
1963              float64
dtype: object

,Country Name,Country Code,Indicator Name,Indicator Code,1960,1961,1962,1963,1964,1965,...,2017,2018,2019,2020,2021,2022,2023,2024,2025,Unnamed: 70
0,Aruba,ABW,GDP per capita (current US$),NY.GDP.PCAP.CD,NaN,NaN,NaN,NaN,NaN,NaN,...,28440.041688,30082.158423,30645.890602,22759.807175,26749.329609,30975.998912,35718.753119,39498.594129,NaN,NaN
1,Africa Eastern and Southern,AFE,GDP per capita (current US$),NY.GDP.PCAP.CD,186.089204,186.909053,197.367547,225.400079,208.962717,226.836135,...,1528.104224,1552.073722,1507.085600,1351.591669,1562.416175,1679.327622,1571.449189,1615.396356,NaN,NaN
2,Afghanistan,AFG,GDP per capita (current US$),NY.GDP.PCAP.CD,NaN,NaN,NaN,NaN,NaN,NaN,...,525.469771,491.337221,496.602504,510.787063,356.496214,357.261153,413.757895,NaN,NaN,NaN
3,Africa Western and Central,AFW,GDP per capita (current US$),NY.GDP.PCAP.CD,121.936832,127.451040,133.823783,139.004980,148.545883,155.561897,...,1574.230564,1720.140092,2216.385055,2030.861659,2112.794076,2138.473153,1841.855064,1411.337029,NaN,NaN
4,Angola,AGO,GDP per capita (current US$),NY.GDP.PCAP.CD,NaN,NaN,NaN,NaN,NaN,NaN,...,2790.718869,2860.093648,2493.678844,1759.356199,2303.908127,3682.113151,2916.136633,2665.874448,NaN,NaN

In [59]:
# Coverage
print('Num of Countries:', wb['Country Name'].nunique())
print('Num of Country Codes:', wb['Country Code'].nunique())
print('Year range: 1960 ~ 2025')

Num of Countries: 266
Num of Country Codes: 266
Year range: 1960 ~ 2025

In [65]:
# Missing values
print(wb.isnull().sum())

Country Name        0
Country Code        0
Indicator Name      0
Indicator Code      0
1960              115
                 ...
2022                9
2023               15
2024               26
2025              266
Unnamed: 70       266
Length: 71, dtype: int64

In [66]:
# Duplicates
print(wb.duplicated().sum())

0

In [70]:
# GDP Distribution by year
print(wb.describe())

              1960         1961         1962         1963         1964  \
count   151.000000   154.000000   156.000000   156.000000   156.000000
mean    471.801812   491.169565   538.650484   571.509413   617.797769
std     593.004639   616.999240   729.010673   753.033032   811.026840
min      25.084776    27.265454    27.947004    25.803984    17.332201
25%     123.298251   127.469973   129.546141   138.894446   144.547396
50%     221.559849   209.531940   217.376949   233.409578   244.104274
75%     499.867270   538.358099   574.686135   610.222254   707.377633
max    2999.864872  3059.160821  4748.392844  4444.523086  4378.784298

              1965         1966         1967         1968         1969  ...  \
count   162.000000   163.000000   167.000000   168.000000   168.000000  ...
mean    672.917147   716.784470   730.132376   763.880229   827.500201  ...
std     840.675732   907.766379   938.440133   984.135076  1060.382766  ...
min      15.117863    11.801322    16.545381    21.545341    21.510318  ...
25%     155.774300   164.134108   162.377365   166.230264   175.154789  ...
50%     271.540924   282.446374   283.733706   301.234016   316.067555  ...
75%     851.125067   895.792733   844.844588   847.350025   901.091256  ...
max    4023.990378  4176.110382  4325.959351  4684.588403  5019.998186  ...

                2017           2018           2019           2020  \
count     259.000000     259.000000     259.000000     258.000000
mean    16592.499881   17573.925150   17537.480522   16283.153813
std     24429.210650   25930.239350   25636.630243   24311.651161
min       246.060726     245.661678     234.310616     255.832454
25%      2163.095257    2163.093927    2227.362557    2133.015667
50%      6233.322448    6713.989254    6718.858266    6131.818702
75%     20839.226799   22413.498842   22627.756511   19908.734345
max    170663.375248  188298.315668  193746.785647  176891.886538

                2021           2022           2023           2024  2025  \
count     258.000000     257.000000     251.000000     240.000000   0.0
mean    18803.437185   19476.548373   20172.185789   19724.631062   NaN
std     28779.971299   28996.961493   30917.462749   30040.258015   NaN
min       264.980379     302.992505     250.627253     219.424831   NaN
25%      2462.698252    2536.400502    2541.703814    2619.263802   NaN
50%      7001.419123    7606.237525    7802.824333    7836.504782   NaN
75%     22009.595072   24387.038729   23979.291930   24745.502555   NaN
max    223823.363960  226052.001905  256799.788613  288001.433369   NaN

       Unnamed: 70
count          0.0
mean           NaN
std            NaN
min            NaN
25%            NaN
50%            NaN
75%            NaN
max            NaN

[8 rows x 67 columns]